@startuml
abstract class AICombatControllerBase {
    + AICombatControllerBase(creepController:CreepController, creep:Creep)
    + Attack(targetableView:TargetableView) : void
    + Cancel() : void
}
BaseCombatController <|-- AICombatControllerBase
@enduml
