@startuml
class PopupSystem {
    + Initialize(container:DiContainer) : void
    + SpawnPopup(layer:int) : T
    + DeletePopUp() : void
    + DeleteAllPopups() : void
}
MonoBehaviour <|-- PopupSystem
@enduml
