@startuml
enum Characteristic {
    Damage,
    AttackSpeed,
    MovingSpeed,
    Defense,
    Mana,
    Health,
    GoldGenerationPerSecond,
    ManaGenerationPerSecond,
    HealthGenerationPerSecond,
}
@enduml
