@startuml
class LogProgressManager {
    + CreateProgress(name:string, description:string, isIndefinite:bool) : int
    + ReportProgress(id:int, progressValue:float, description:string) : void
    + FinishProgress(id:int) : void
}
IProgressManager <|-- LogProgressManager
@enduml
