@startuml
class FactoryFromBinderUntyped {
    + FactoryFromBinderUntyped(bindContainer:DiContainer, contractType:Type, bindInfo:BindInfo, factoryBindInfo:FactoryBindInfo)
}
FactoryFromBinderBase <|-- FactoryFromBinderUntyped
@enduml
