@startuml
class EnemyTargetingInputs {
    +  <<event>> OnTargetedEnemy : Action<TargetableView> 
    + EnemyTargetingInputs(camera:Camera, characterView:CharacterView)
    + CheckTargetOnClick() : void
}
@enduml
