@startuml
class RangeTargetZoneSkillObserver {
    +  <<event>> OnSkillCalled : Action<Vector3> 
    +  <<event>> OnObservedPositionChanged : Action<Vector3> 
    + RangeTargetZoneSkillObserver(camera:Camera)
    + <<async>> ObserveSkill(cancellationToken:CancellationTokenSource) : UniTask
}
ISkillObserver <|-- RangeTargetZoneSkillObserver
@enduml
