@startuml
class "FactoryToChoiceIdBinder`5"<TParam1,TParam2,TParam3,TParam4,TContract> {
    + FactoryToChoiceIdBinder(bindContainer:DiContainer, bindInfo:BindInfo, factoryBindInfo:FactoryBindInfo)
    + WithId(identifier:object) : FactoryArgumentsToChoiceBinder<TParam1, TParam2, TParam3, TParam4, TContract>
}
class "FactoryArgumentsToChoiceBinder`5"<T1,T2,T3,T4,T5> {
}
"FactoryArgumentsToChoiceBinder`5" "<TParam1,TParam2,TParam3,TParam4,TContract>" <|-- "FactoryToChoiceIdBinder`5"
@enduml
