@startuml
class ScriptableObjectResourceProvider {
    <<readonly>> _resourcePath : string
    <<readonly>> _createNew : bool
    <<readonly>> _concreteIdentifier : object
    + ScriptableObjectResourceProvider(resourcePath:string, resourceType:Type, container:DiContainer, extraArguments:IEnumerable<TypeValuePair>, createNew:bool, concreteIdentifier:object, instantiateCallback:Action<InjectContext, object>)
    + IsCached : bool <<get>>
    + TypeVariesBasedOnMemberType : bool <<get>>
    + GetInstanceType(context:InjectContext) : Type
    + GetAllInstancesWithInjectSplit(context:InjectContext, args:List<TypeValuePair>, injectAction:Action, buffer:List<object>) : void
}
class "List`1"<T> {
}
class "Action`2"<T1,T2> {
}
IProvider <|-- ScriptableObjectResourceProvider
ScriptableObjectResourceProvider --> "_container" DiContainer
ScriptableObjectResourceProvider --> "_resourceType" Type
ScriptableObjectResourceProvider --> "_extraArguments<TypeValuePair>" "List`1"
ScriptableObjectResourceProvider --> "_instantiateCallback<InjectContext,object>" "Action`2"
@enduml
