@startuml
class MeleeCharacterCombatController {
    + MeleeCharacterCombatController(characterController:ICharacterController, character:Models.Character)
}
CharacterCombatController <|-- MeleeCharacterCombatController
@enduml
