@startuml
class NullBindingFinalizer {
    + FinalizeBinding(container:DiContainer) : void
}
IBindingFinalizer <|-- NullBindingFinalizer
NullBindingFinalizer --> "BindingInheritanceMethod" BindingInheritanceMethods
@enduml
