@startuml
class PrefabResourceBindingFinalizer {
    <<readonly>> _resourcePath : string
    + PrefabResourceBindingFinalizer(bindInfo:BindInfo, gameObjectBindInfo:GameObjectCreationParameters, resourcePath:string, providerFactory:Func<Type, IPrefabInstantiator, IProvider>)
    FinalizeBindingConcrete(container:DiContainer, concreteTypes:List<Type>) : void
    FinalizeBindingSelf(container:DiContainer) : void
}
class "Func`3"<T1,T2,T3> {
}
ProviderBindingFinalizer <|-- PrefabResourceBindingFinalizer
PrefabResourceBindingFinalizer --> "_gameObjectBindInfo" GameObjectCreationParameters
PrefabResourceBindingFinalizer --> "_providerFactory<Type,IPrefabInstantiator,IProvider>" "Func`3"
@enduml
