@startuml
class SubContainerBindingFinalizer {
    <<readonly>> _subIdentifier : object
    <<readonly>> _resolveAll : bool
    + SubContainerBindingFinalizer(bindInfo:BindInfo, subIdentifier:object, resolveAll:bool, creatorFactory:Func<DiContainer, ISubContainerCreator>)
    FinalizeBindingConcrete(container:DiContainer, concreteTypes:List<Type>) : void
    FinalizeBindingSelf(container:DiContainer) : void
}
class "Func`2"<T1,T2> {
}
ProviderBindingFinalizer <|-- SubContainerBindingFinalizer
SubContainerBindingFinalizer --> "_creatorFactory<DiContainer,ISubContainerCreator>" "Func`2"
@enduml
