@startuml
class CreepViewFactory {
    + <<override>> Create(requirement:DefaultFactoryRequirement) : CreepView
}
class "ViewFactoryBase`2"<T1,T2> {
}
"ViewFactoryBase`2" "<CreepView,DefaultFactoryRequirement>" <|-- CreepViewFactory
@enduml
