@startuml
class "MonoPoolableMemoryPool`1"<TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`2"<TParam1,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`3"<TParam1,TParam2,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`4"<TParam1,TParam2,TParam3,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`5"<TParam1,TParam2,TParam3,TParam4,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`6"<TParam1,TParam2,TParam3,TParam4,TParam5,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`7"<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`8"<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TParam7,TValue> {
    + MonoPoolableMemoryPool()
}
class "MonoPoolableMemoryPool`9"<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TParam7,TParam8,TValue> {
    + MonoPoolableMemoryPool()
}
class "MemoryPool`1"<T> {
}
class "MemoryPool`2"<T1,T2> {
}
class "IPoolable`1"<T> {
}
class "MemoryPool`3"<T1,T2,T3> {
}
class "IPoolable`2"<T1,T2> {
}
class "MemoryPool`4"<T1,T2,T3,T4> {
}
class "IPoolable`3"<T1,T2,T3> {
}
class "MemoryPool`5"<T1,T2,T3,T4,T5> {
}
class "IPoolable`4"<T1,T2,T3,T4> {
}
class "MemoryPool`6"<T1,T2,T3,T4,T5,T6> {
}
class "IPoolable`5"<T1,T2,T3,T4,T5> {
}
class "MemoryPool`7"<T1,T2,T3,T4,T5,T6,T7> {
}
class "IPoolable`6"<T1,T2,T3,T4,T5,T6> {
}
class "MemoryPool`8"<T1,T2,T3,T4,T5,T6,T7,T8> {
}
class "IPoolable`7"<T1,T2,T3,T4,T5,T6,T7> {
}
class "MemoryPool`9"<T1,T2,T3,T4,T5,T6,T7,T8,T9> {
}
class "IPoolable`8"<T1,T2,T3,T4,T5,T6,T7,T8> {
}
"MemoryPool`1" "<TValue>" <|-- "MonoPoolableMemoryPool`1"
"MonoPoolableMemoryPool`1" --> "_originalParent" Transform
"MemoryPool`2" "<TParam1,TValue>" <|-- "MonoPoolableMemoryPool`2"
"MonoPoolableMemoryPool`2" --> "_originalParent" Transform
"MemoryPool`3" "<TParam1,TParam2,TValue>" <|-- "MonoPoolableMemoryPool`3"
"MonoPoolableMemoryPool`3" --> "_originalParent" Transform
"MemoryPool`4" "<TParam1,TParam2,TParam3,TValue>" <|-- "MonoPoolableMemoryPool`4"
"MonoPoolableMemoryPool`4" --> "_originalParent" Transform
"MemoryPool`5" "<TParam1,TParam2,TParam3,TParam4,TValue>" <|-- "MonoPoolableMemoryPool`5"
"MonoPoolableMemoryPool`5" --> "_originalParent" Transform
"MemoryPool`6" "<TParam1,TParam2,TParam3,TParam4,TParam5,TValue>" <|-- "MonoPoolableMemoryPool`6"
"MonoPoolableMemoryPool`6" --> "_originalParent" Transform
"MemoryPool`7" "<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TValue>" <|-- "MonoPoolableMemoryPool`7"
"MonoPoolableMemoryPool`7" --> "_originalParent" Transform
"MemoryPool`8" "<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TParam7,TValue>" <|-- "MonoPoolableMemoryPool`8"
"MonoPoolableMemoryPool`8" --> "_originalParent" Transform
"MemoryPool`9" "<TParam1,TParam2,TParam3,TParam4,TParam5,TParam6,TParam7,TParam8,TValue>" <|-- "MonoPoolableMemoryPool`9"
"MonoPoolableMemoryPool`9" --> "_originalParent" Transform
@enduml
