@startuml
class MonoInstallerBase {
    + <<virtual>> IsEnabled : bool <<get>>
    + <<virtual>> Start() : void
    + <<virtual>> InstallBindings() : void
}
MonoBehaviour <|-- MonoInstallerBase
IInstaller <|-- MonoInstallerBase
@enduml
