@startuml
class MonoInstaller {
}
class "MonoInstaller`1"<TDerived> {
    + {static} InstallFromResource(container:DiContainer) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer) : TDerived
    + {static} InstallFromResource(container:DiContainer, extraArgs:object[]) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, extraArgs:object[]) : TDerived
}
class "MonoInstaller`2"<TParam1,TDerived> {
    + {static} InstallFromResource(container:DiContainer, p1:TParam1) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, p1:TParam1) : TDerived
}
class "MonoInstaller`3"<TParam1,TParam2,TDerived> {
    + {static} InstallFromResource(container:DiContainer, p1:TParam1, p2:TParam2) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, p1:TParam1, p2:TParam2) : TDerived
}
class "MonoInstaller`4"<TParam1,TParam2,TParam3,TDerived> {
    + {static} InstallFromResource(container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3) : TDerived
}
class "MonoInstaller`5"<TParam1,TParam2,TParam3,TParam4,TDerived> {
    + {static} InstallFromResource(container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3, p4:TParam4) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3, p4:TParam4) : TDerived
}
class "MonoInstaller`6"<TParam1,TParam2,TParam3,TParam4,TParam5,TDerived> {
    + {static} InstallFromResource(container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3, p4:TParam4, p5:TParam5) : TDerived
    + {static} InstallFromResource(resourcePath:string, container:DiContainer, p1:TParam1, p2:TParam2, p3:TParam3, p4:TParam4, p5:TParam5) : TDerived
}
class MonoInstallerUtil <<static>> {
    + {static} GetDefaultResourcePath() : string
    + {static} CreateInstaller(resourcePath:string, container:DiContainer) : TInstaller
}
MonoInstallerBase <|-- MonoInstaller
MonoInstaller <|-- "MonoInstaller`1"
MonoInstallerBase <|-- "MonoInstaller`2"
MonoInstallerBase <|-- "MonoInstaller`3"
MonoInstallerBase <|-- "MonoInstaller`4"
MonoInstallerBase <|-- "MonoInstaller`5"
MonoInstallerBase <|-- "MonoInstaller`6"
@enduml
