@startuml
class NewToolbarCompositeAltActionProvider {
    + NewToolbarCompositeAltActionProvider(tools:IEnumerable<IPartialAltActionProvider>)
    + <<override>> IsAvailable() : bool
}
CompositeAltActionProvider <|-- NewToolbarCompositeAltActionProvider
@enduml
