@startuml
class VisualElementToolbarDisplay {
    + VisualElementToolbarDisplay(toolbox:Overlay)
    + OpenToolbox() : void
    + CloseToolbox() : void
}
ISceneToolbarDisplay <|-- VisualElementToolbarDisplay
@enduml
