@startuml
class "FactoryFromBinder`6"<TParam1,TParam2,TParam3,TParam4,TParam5,TContract> {
    + FactoryFromBinder(container:DiContainer, bindInfo:BindInfo, factoryBindInfo:FactoryBindInfo)
    + FromMethod(method:ModestTree.Util.
#endif
            Func<DiContainer, TParam1, TParam2, TParam3, TParam4, TParam5, TContract>) : ConditionCopyNonLazyBinder
    + FromFactory() : ConditionCopyNonLazyBinder
    + FromSubContainerResolve() : FactorySubContainerBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>
    + FromSubContainerResolve(subIdentifier:object) : FactorySubContainerBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>
}
class FactoryFromBinder5Extensions <<static>> {
    + {static} FromIFactory(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>, factoryBindGenerator:Action<ConcreteBinderGeneric<IFactory<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>>>) : ArgConditionCopyNonLazyBinder
    + {static} FromPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>) : ArgConditionCopyNonLazyBinder
    + {static} FromPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>, poolBindGenerator:Action<MemoryPoolInitialSizeMaxSizeBinder<TContract>>) : ArgConditionCopyNonLazyBinder
    + {static} FromMonoPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>) : ArgConditionCopyNonLazyBinder
    + {static} FromMonoPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>, poolBindGenerator:Action<MemoryPoolInitialSizeMaxSizeBinder<TContract>>) : ArgConditionCopyNonLazyBinder
    + {static} FromPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>) : ArgConditionCopyNonLazyBinder
    + {static} FromPoolableMemoryPool(fromBinder:FactoryFromBinder<TParam1, TParam2, TParam3, TParam4, TParam5, TContract>, poolBindGenerator:Action<MemoryPoolInitialSizeMaxSizeBinder<TContract>>) : ArgConditionCopyNonLazyBinder
}
FactoryFromBinderBase <|-- "FactoryFromBinder`6"
@enduml
