@startuml
class ConcreteIdArgConditionCopyNonLazyBinder {
    + ConcreteIdArgConditionCopyNonLazyBinder(bindInfo:BindInfo)
    + WithConcreteId(id:object) : ArgConditionCopyNonLazyBinder
}
ArgConditionCopyNonLazyBinder <|-- ConcreteIdArgConditionCopyNonLazyBinder
@enduml
