@startuml
class DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder {
    + DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder(subContainerBindInfo:SubContainerCreatorBindInfo, bindInfo:BindInfo)
    + WithDefaultGameObjectParent(defaultParentName:string) : ScopeConcreteIdArgConditionCopyNonLazyBinder
}
ScopeConcreteIdArgConditionCopyNonLazyBinder <|-- DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder
@enduml
