@startuml
class WithKernelDefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder {
    + WithKernelDefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder(subContainerBindInfo:SubContainerCreatorBindInfo, bindInfo:BindInfo)
    + WithKernel() : DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder
    + WithKernel() : DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder
}
DefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder <|-- WithKernelDefaultParentScopeConcreteIdArgConditionCopyNonLazyBinder
@enduml
